apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T07:50:44Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3396"
  uid: a3c9efac-4e99-4f75-acb2-b44f60388121
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.72.167
  clusterIPs:
  - 10.111.72.167
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31407
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
